wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.14.2
    framework: huggingface
    huggingface_version: 4.28.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682061385.858821
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 70
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 70
      3:
      - 1
      - 13
      - 23
      4: 3.9.12
      5: 0.14.2
      6: 4.28.0.dev0
      8:
      - 5
